- name: 1. Zorg dat de MariaDB service draait en actief is
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

- name: 2. Creëer de WordPress database uit variabele
  community.mysql.mysql_db:
    name: "wordpress_database"
    state: present
    # Gebruik de socket voor lokale root-connectie (veiliger dan een DB root wachtwoord in de playbook)
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: 3. Maak de databasegebruiker aan en geef rechten op de database
  community.mysql.mysql_user:
    name: "wordpress_gebruiker"
    password: "Poepaap123"
    priv: "wordpress_database.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock


- name: 4. Genereer wp-config.php van de template
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: "var/www/html/wp-config.php"
    owner: root
    group: root
    mode: '0644'

- name: 5. Stel www-data in als eigenaar en groep van de WordPress-bestanden
  ansible.builtin.file:
    path: "var/www/html"
    owner: www-data
    group: www-data
    recurse: yes
    state: directory

- name: 6. Stel schrijfpermissies (0775) in voor essentiële mappen
  ansible.builtin.file:
    path: "/var/www/html/{{ item }}"
    owner: www-data
    group: www-data
    mode: '0775'
    state: directory
    recurse: yes
  loop:
    - wp-content
    - wp-admin
    - wp-includes
