---
- name: configureer syslog server
  hosts: localhost
  become: yes
  gather_facts: false
  roles:
    - { role: syslog_server, tags: ["syslog_server"] }


- name: configureer syslog client
  hosts: clients
  vars:
    syslog_server: 172.16.0.4
  become: yes
  gather_facts: false
  roles:
    - { role: syslog_client, tags: ["syslog_clients"] }

