---
- name: configureer wordpress
  hosts: clients
  become: yes
  gather_facts: false
  roles:
    - { role: wordpress, tags: ["wordpress"] }
    - { role: wordpress_user, tags: ["wordpress_user"] }
    - { role: mariadb, tags: ["mariadb"] }
    - { role: apache2, tags: ["apache2"] }
